### ISSUE TITLE
release as deb package for hydro

### ISSUE THREAD

**Issue by k-okada** [PR2/pr2_navigation#4]
if someone create pr2_navigagtion-release repository, I think I can help you, to run bloom to create configuration files and send PR to you.

**Comment by UltronDestroyer** [comment]
Hi k-okada,

has this been tested at all? I think it's missing testing on a real robot and with simulation. I'm going to go ahead and release this anyway as I don't believe anyone will be using it immediately or trying to at least.

**Comment by k-okada** [comment]
No I have not tested, but due to everyone is talking that EOL of groovy,  I think we should release this ans ask for testing on real robot and/or simulation.

**Comment by UltronDestroyer** [comment]
Sure. I attempted to release this on Thursday-ish, but I ran into some permissions issues with the bloom command. Are you able to release this? The repo for pr2_navigation has been created

**Comment by k-okada** [comment]
ok, but could you give me a permission to pr2_navigation-release repo? or could you show me the error message of the bloom command?

**Comment by UltronDestroyer** [comment]
https://github.com/orgs/PR2/teams/package-release

Added to package-release teams. Let me know if you need anything else to release the package.

**Comment by airballking** [comment]
@k-okada At Bremen, we have so far run our navigation and localization code still under Groovy. Today, we played around with the new catkinized code out of the hydro-devel branch of this repo. Thanks for providing this! However, we ran into several problems, e.g. compilation of pr2_navigation_self_test, running stuff out of the overlay on c2, finding some of the plugins...

Before we try to debug these issues in Bremen, have you already got this meta-package running and working in your lab? If yes, what setup or top-level launch-file do you use? If no, I'll keep you posted and provide pull requests as we go along. :)

Just for reference, here is the relevant excerpt out of our launch-file (so that you know what we tried to run):

```
<include file="$(find pr2_machine)/$(env ROBOT).machine" />
<include file="$(find pr2_navigation_global)/amcl_node.xml" />
<include file="$(find pr2_navigation_teleop)/teleop.xml" />
<include file="$(find pr2_navigation_perception)/lasers_and_filters.xml" />
<include file="$(find pr2_navigation_perception)/ground_plane.xml" />
<include file="$(find pr2_navigation_global)/move_base.xml" />
```

**Comment by k-okada** [comment]
Unfortunately I haven't test these code, just to confirm it is working in catkin, I'll check this on our robot during this week with @aginika

**Comment by aginika** [comment]
@airballking You may have resolved the problems already, but we tested on the real robot with rviz 2d_nav_goal and made sure that navigation seems to work in our environment. Lasers are correctly took into account and the obstacles is shown in costmaps.
We launched the below launch file (please ignore the jsk_maps include file, that is our map server and static tf publishers)

```
<launch>
  <include file="$(find pr2_machine)/$(env ROBOT).machine" />
  <include file="$(find jsk_maps)/launch/start_map_eng2.launch">
    <arg name="MACHINE" value="c2" />
  </include>
  <include file="$(find pr2_navigation_global)/amcl_node.xml" />
  <include file="$(find pr2_navigation_teleop)/teleop.xml" />
  <include file="$(find pr2_navigation_perception)/lasers_and_filters.xml" />
  <include file="$(find pr2_navigation_perception)/ground_plane.xml" />
  <include file="$(find pr2_navigation_global)/move_base.xml" />
</launch>
```

Sorry for being late.
